services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-fpm
    volumes:
      - ./build:/var/www/html
      - /var/log/supervisor:/var/log/supervisor
    networks:
      - lite-network

  php-nginx:
    image: nginx:latest
    container_name: php-deploy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./build:/var/www/html
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf
      - ./deply/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - php-fpm
    networks:
      - lite-network

networks:
  lite-network:
    driver: bridge