services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-fpm
    volumes:
      - ./build:/var/www/html
    networks:
      - lite-network

  php-nginx:
    image: nginx:latest
    container_name: php-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./build:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - php-fpm
    networks:
      - lite-network

networks:
  lite-network:
    driver: bridge